function generateIntervalleyScatteringRate(obj, dv, pc, cc)
    %% 生成谷间散射率句柄函数
    %>     参数说明：
    %>     w：某极化支/某散射类型的声子平均频率
    %>     de：散射终态能谷与散射初态能谷极小值之差
    %>     DK：耦合常数
    %>     Zf：某一类型散射可供选择的等效能谷数
    %>     
    % ======================================================================
    epsilongTempAB = @(w, de) dv.bs.epsilong + pc.hbar * w - de;
    obj.interScatRateAB = @(DK, Zf, w, de) DK^2*obj.md^(3/2) * Zf ... 
                                  / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                  * (1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                  * real(sqrt(epsilongTempAB(w, de)*(1 + dv.bs.alpha*epsilongTempAB(w, de)/pc.e))) ...
                                  * (1 + 2*dv.bs.alpha*epsilongTempAB(w, de)/pc.e);
    epsilongTempEM = @(w, de) dv.bs.epsilong - pc.hbar * w - de;
    obj.interScatRateEM = @(DK, Zf, w, de) DK^2*obj.md^(3/2) * Zf ... 
                                  / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                  * (1 + 1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                  * real(sqrt(epsilongTempEM(w, de)*(1 + dv.bs.alpha*epsilongTempEM(w, de)/pc.e))) ...
                                  * (1 + 2*dv.bs.alpha*epsilongTempEM(w, de)/pc.e);
                              
end