function generateIntravalleyOpticalScatteringRate(obj, dv, pc, cc)
    %% 生成谷内光学散射句柄函数
    %>     参数说明：
    %>     
    % ======================================================================
    epsilongTempAB = @(w) dv.bs.epsilong + pc.hbar * w;
    obj.intraOpticalScatRateAB = @(DK, w) DK^2*obj.md^(3/2) ... 
                                            / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                           * (1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                           * real(sqrt(epsilongTempAB(w)*(1 + dv.bs.alpha*epsilongTempAB(w)/pc.e))) ...
                                           * (1 + 2*dv.bs.alpha*epsilongTempAB(w)/pc.e);
    epsilongTempEM = @(w) dv.bs.epsilong - pc.hbar * w;
    obj.intraOpticalScatRateEM = @(DK, w) DK^2*obj.md^(3/2) ... 
                                            / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                           * (1 + 1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                           * real(sqrt(epsilongTempEM(w)*(1 + dv.bs.alpha*epsilongTempEM(w)/pc.e))) ...
                                           * (1 + 2*dv.bs.alpha*epsilongTempEM(w)/pc.e);
    
end