function interScatteringRate(obj, es, dv, pc, cc)
    %> 谷间散射
    gamma = @(w, dE) dv.bs.epsilong * (1 + real(dv.bs.epsilong + pc.hbar * w - dE)/pc.e * dv.bs.alpha);
    obj.interScatRateAB = @(DK, Zf, w, dE) DK^2*obj.md^(3/2) * Zf ... 
                                  / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                  * (1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                  * gamma(w, dE)^(1/2) ...
                                  * (1 + 2*dv.bs.alpha*real(dv.bs.epsilong + pc.hbar * w - dE));
    gamma = @(w, dE) dv.bs.epsilong * (1 + real(dv.bs.epsilong - pc.hbar * w - dE)/pc.e * dv.bs.alpha);
    obj.interScatRateEM = @(DK, Zf, w, dE) DK^2*obj.md^(3/2) * Zf ... 
                                  / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                  * (1 + 1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                  * gamma(w, dE)^(1/2) ...
                                  * (1 + 2*dv.bs.alpha*real(dv.bs.epsilong - pc.hbar * w - dE));
    
end