function intravalleyOpticalScatteringRate(obj, es, dv, pc, cc)
    %> 谷内光学散射
    gamma = es.energy - dv.bs.Eg;
    obj.intraOpticalScatRateAB = @(DK, w) DK^2*obj.md^(3/2) ... 
                                            / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                           * (1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                           * gamma^(1/2)*real(dv.bs.epsilong + pc.hbar * w) ...
                                           * (1 + 2*dv.bs.alpha*real(dv.bs.epsilong + pc.hbar * w));
    obj.intraOpticalScatRateEM = @(DK, w) DK^2*obj.md^(3/2) ... 
                                            / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                           * (1 + 1/(exp(pc.hbar * w / (pc.kb*cc.envTemp)) - 1)) ...
                                           * gamma^(1/2)*real(dv.bs.epsilong - pc.hbar * w) ...
                                           * (1 + 2*dv.bs.alpha*real(dv.bs.epsilong - pc.hbar * w));
    
end