%% 预先声明结构体

Grid     = struct('face', {0},...
                  'point',{0});

Allgrid  = struct('w', {0},...
                  'q', {0},...
                  'x', {0},...
                  't', {0});

Polar    = struct('LA', {0}, ...
                  'TA', {0},...
                  'LO', {0},...
                  'TO', {0});

Electron = struct('r', {[0, 0, 0]},...
                  'k', {[0, 0, 0]},...
                  'v', {[0, 0, 0]},...
                  'charge', {0},...
                  'energy', {0},...
                  'valley', {0},...
                  'type', {0},...
                  'time'  , {0});            
                           
Phonon  =  struct('r', {[0, 0, 0]},...
                  'k', {[0, 0, 0]},...
                  'q', {0},...
                  'w', {0},...
                  'time', {0},...
                  'energy', {0},...
                  'type', {0},...
                  'polarization', {0});
              
Frequency = struct('pop', {0},...
                   'num', {0});
               

           
               
