function inelasticIntervalleyScatteringRate(obj, es, pc, cc)
    %>生成谷间散射率句柄函数
    %>     参数说明：
    %>     DK：耦合常数
    %>     Zf：某一类型散射可供选择的等效能谷数
    %>     w：某极化支/某散射类型的声子平均频率
    %>     de：散射终态能谷与散射初态能谷极小值之差
    %>     
    % ======================================================================
    epsilonTempAB = @(w, de) es.epsilon + pc.hbar * w - de;
    obj.inelasticInterAB = @(DK, Zf, w, de) DK^2*obj.md^(3/2)*Zf ... 
                                  / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                  * (1/(exp(pc.hbar * w/(pc.kb*cc.envTemp)) - 1)) ...
                                  * real(sqrt(epsilonTempAB(w, de))) ...
                                  * real(sqrt((1 + obj.alpha*epsilonTempAB(w, de)/pc.e))) ...
                                  * (1 + 2*obj.alpha*epsilonTempAB(w, de)/pc.e);
    epsilonTempEM = @(w, de) es.epsilon - pc.hbar * w - de;
    obj.inelasticInterEM = @(DK, Zf, w, de) DK^2*obj.md^(3/2)*Zf ... 
                                  / (sqrt(2)*pi*pc.rho*pc.hbar^3 * w) ...
                                  * (1 + 1/(exp(pc.hbar * w/(pc.kb*cc.envTemp)) - 1)) ...
                                  * real(sqrt(epsilonTempEM(w, de))) ...
                                  * real(sqrt((1 + obj.alpha*epsilonTempEM(w, de)/pc.e))) ...
                                  * (1 + 2*obj.alpha*epsilonTempEM(w, de)/pc.e);
end